language: python

matrix:
 include:
  - os: linux
    python: 2.7
    jdk: openjdk7
    env: JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
  - os: linux
    python: 2.7
    jdk: oraclejdk8
    env: JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - os: linux
    python: 2.7
    jdk: oraclejdk9
    env: JAVA_HOME=/usr/lib/jvm/java-9-oracle
  - os: linux
    python: 3.3
    jdk: openjdk7
    env: JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
  - os: linux
    python: 3.3
    jdk: oraclejdk8
    env: JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - os: linux
    python: 3.3
    jdk: oraclejdk9
    env: JAVA_HOME=/usr/lib/jvm/java-9-oracle
  - os: linux
    python: 3.4
    jdk: openjdk7
    env: JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
  - os: linux
    python: 3.4
    jdk: oraclejdk8
    env: JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - os: linux
    python: 3.4
    jdk: oraclejdk9
    env: JAVA_HOME=/usr/lib/jvm/java-9-oracle
  - os: linux
    python: 3.5
    jdk: openjdk7
    env: JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
  - os: linux
    python: 3.5
    jdk: oraclejdk8
    env: JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - os: linux
    python: 3.5
    jdk: oraclejdk9
    env: JAVA_HOME=/usr/lib/jvm/java-9-oracle
  - os: linux
    python: 3.6
    jdk: openjdk7
    env: JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
  - os: linux
    python: 3.6
    jdk: oraclejdk8
    env: JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - os: linux
    python: 3.6
    jdk: oraclejdk9
    env: JAVA_HOME=/usr/lib/jvm/java-9-oracle
   # Force error for earlier detection of python 2.7 windows build problems
  - os: linux
    python: 2.7
    jdk: oraclejdk9
    env:
      - JAVA_HOME=/usr/lib/jvm/java-9-oracle
      - CFLAGS="-Wdeclaration-after-statement -Werror=declaration-after-statement"
  - os: osx
    language: generic


script: ./setup.py test
